In [ ]:
# import pandas as pdfrompandas
from pandas import DataFrame as df

import numpy as np
import scipy
import patsy
import pytest 
# %matplotlib inline
import matplotlib.pyplot as plt
import factor_analyzer  
from factor_analyzer.factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
from factor_analyzer.factor_analyzer import calculate_kmo
from factor_analyzer.factor_analyzer import Rotator

import statsmodels 
from statsmodels.multivariate.factor import Factor 
from statsmodels.multivariate.factor import FactorResults
import sklearn as sk 
from sklearn.decomposition import FactorAnalysis
import statsmodels.formula.api as smf #Libreria que permite calcular los datos

import statsmodels.api
big_five=statsmodels.api.datasets.get_rdataset("Duncan","carData")
print(big_five.__doc__)
bfi=big_five.data
bfi.info()
bfi.head(5)

In [2]:
bfi.drop(columns=['type'],inplace=True)
bfi.dropna(inplace=True)
bfi.describe()

          income   education   prestige
count  45.000000   45.000000  45.000000
mean   41.866667   52.555556  47.688889
std    24.435072   29.760831  31.510332
min     7.000000    7.000000   3.000000
25%    21.000000   26.000000  16.000000
50%    42.000000   45.000000  41.000000
75%    64.000000   84.000000  81.000000
max    81.000000  100.000000  97.000000

In [3]:
corr=df(bfi.corr(method='pearson'))
corr

             income  education  prestige
income     1.000000   0.724512  0.837801
education  0.724512   1.000000  0.851916
prestige   0.837801   0.851916  1.000000

In [6]:
np.linalg.det(corr)

0.0005640638658997563

In [5]:
skewness=df(scipy.stats.skew(bfi,nan_policy='omit'),columns=['Skewness'])
skewness

   Skewness
0  0.109868
1  0.226217
2  0.141590

In [9]:
kurtosis=df(scipy.stats.kurtosis(bfi,nan_policy='omit'),columns=["Kurtosis"])
kurtosis

    Kurtosis
0  -0.277667
1   1.009703
2   0.467126
3   0.018136
4   0.129488
5   0.325008
6  -0.149700
7  -0.145029
8  -0.586959
9  -1.230785
10 -1.091763
11 -1.150102
12 -0.457785
13 -0.317608
14 -0.108533
15 -1.019244
16 -1.057062
17 -1.179222
18 -1.083444
19 -1.066112
20  0.460237
21 -0.761683
22  0.324552
23  1.178908
24 -0.182155

In [6]:
skl=FactorAnalysis(n_components=5)
skl.fit(bfi)

FactorAnalysis(n_components=5)

In [7]:
df(skl.components_)

           0          1          2
0  21.484728  27.450471  30.214391
1   9.559989  -9.900503   2.196957
2  -5.460543  -3.671020   7.218067

In [17]:
df(skl.components_).T

           0         1         2         3         4
0   0.321715  0.049436  0.157790 -0.006804  0.452106
1  -0.470559 -0.414929 -0.159156  0.133525 -0.389162
2  -0.610683 -0.521306 -0.279499  0.132316 -0.421511
3  -0.576319 -0.307824 -0.097135  0.401224 -0.286547
4  -0.697106 -0.372615 -0.303554  0.069001 -0.263136
5  -0.354353 -0.243699  0.573866  0.045532 -0.048849
6  -0.346337 -0.331955  0.675653  0.205830 -0.142629
7  -0.360289 -0.165859  0.521798  0.316976 -0.095589
8   0.607214  0.035895 -0.704958 -0.238953 -0.064302
9   0.792757  0.003630 -0.581283 -0.421567 -0.176409
10  0.585581  0.499126  0.398828  0.088340 -0.470546
11  0.947911  0.371377  0.303199 -0.005319 -0.535999
12 -0.608016 -0.584591 -0.160551 -0.260182  0.057060
13 -0.815040 -0.481238 -0.409827  0.193265  0.215765
14 -0.554962 -0.571008  0.165021 -0.068671  0.268768
15  0.948176 -0.895677  0.048423  0.136062  0.274224
16  0.892267 -0.840265  0.123640  0.055186  0.201220
17  0.843873 -0.773467  0.018987  0.036218 -0.146618
18  0.924768 -0.360805  0.038402 -0.158489 -0.449287
19  0.678866 -0.481953 -0.043408  0.258224 -0.356226
20 -0.304801 -0.276321  0.174983 -0.461023 -0.023244
21  0.296518 -0.049607 -0.401229  0.599766 -0.043013
22 -0.399455 -0.417195  0.122513 -0.591827 -0.024758
23  0.133175 -0.206845  0.151114 -0.353381 -0.374043
24  0.230819  0.094069 -0.293274  0.573457  0.067114

In [8]:
df(skl.transform(bfi))

           0         1         2
0   1.121315 -0.324024  0.155048
1   1.107485  0.683976  0.044283
2   1.443395  0.098290 -0.210831
3   1.017100 -0.937134 -0.050033
4   1.255030 -0.136072  0.640797
5   0.752742 -2.173920  2.928182
6   1.387859 -0.457280  0.598855
7   1.596999 -0.062559 -0.798737
8   0.758916 -0.467484 -2.412692
9   1.307378  0.233145  0.037852
10  0.409977 -0.976132 -0.127008
11  1.516655 -0.168254 -0.570859
12  1.617295 -0.027524  0.066269
13  0.557203 -1.509686 -0.301432
14  0.916779 -1.364359  0.083777
15 -0.032295  2.503266 -1.952434
16  0.416713  1.246859  1.777012
17  0.700138  1.088075  1.335963
18 -0.147124  0.410119  0.116925
19  1.373118  0.774785  0.149820
20 -0.002446 -1.713809 -0.662268
21 -0.100857  0.022329 -1.465565
22  0.275418 -0.367496 -1.947270
23 -0.612508 -0.857012 -1.546688
24 -0.800103  0.311713  1.207715
25 -0.047602  0.998513  0.623147
26  0.352358  3.378674  0.164362
27 -0.192094  0.859871  1.812380
28 -0.902246  0.332620  0.664987
29 -0.598982  1.291487 -0.470876
30 -1.109698 -0.545145 -0.403150
31 -1.403125  0.235003  1.262269
32 -0.748188  1.030321 -1.144469
33 -1.299180 -0.331843  0.317571
34 -1.187083  0.492337  0.014771
35 -0.966508  0.362568  0.648040
36 -0.996370 -0.231525  0.403257
37 -1.155075 -0.479228 -0.646357
38 -1.424308 -0.309192 -0.130427
39 -1.124893 -0.171629  0.369364
40 -1.183845 -0.787761 -0.570812
41 -1.126897 -0.233124 -0.289232
42 -1.334852 -0.502988  0.243022
43 -0.245941 -0.178742  0.156337
44 -1.141657 -1.040030 -0.120865

In [9]:
skl.get_params(deep=True)

{'copy': True,
 'iterated_power': 3,
 'max_iter': 1000,
 'n_components': 5,
 'noise_variance_init': None,
 'random_state': 0,
 'rotation': None,
 'svd_method': 'randomized',
 'tol': 0.01}

In [20]:
df(skl.get_covariance())

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1.974778,-0.373863,-0.457807,-0.348235,-0.410023,-0.057893,-0.087105,-0.087149,0.058444,0.086614,...,0.391457,0.355623,0.169712,0.083688,0.024917,-0.091480,0.006105,-0.136971,-0.110239,0.059073
1,-0.373863,1.387799,0.729855,0.579464,0.642567,0.201617,0.276165,0.234833,-0.195307,-0.269668,...,-0.170787,-0.161831,-0.017286,-0.137878,0.060547,0.177718,0.041735,0.272186,0.097487,-0.050517
2,-0.457807,0.729855,1.722007,0.713440,0.824845,0.209660,0.283063,0.242877,-0.197006,-0.304970,...,-0.223233,-0.218929,-0.050840,-0.218975,0.033126,0.230073,0.054414,0.359312,0.095171,-0.060438
3,-0.348235,0.579464,0.713440,2.201500,0.649027,0.255761,0.359609,0.362581,-0.369971,-0.520129,...,-0.299431,-0.303104,-0.193548,-0.360475,-0.032989,0.065411,0.136320,0.116376,-0.062361,0.077358
4,-0.410023,0.642567,0.824845,0.649027,1.615141,0.179624,0.211761,0.201592,-0.222242,-0.360206,...,-0.404705,-0.395581,-0.264747,-0.414590,-0.168928,0.236628,-0.013723,0.362405,0.012405,-0.085023
5,-0.057893,0.201617,0.209660,0.255761,0.179624,1.523890,0.607696,0.486633,-0.636206,-0.625956,...,-0.097126,-0.047771,-0.090829,-0.202999,-0.118859,0.255907,-0.293825,0.287787,0.092117,-0.250184
6,-0.087105,0.276165,0.283063,0.359609,0.211761,0.607696,1.739124,0.611271,-0.738536,-0.730121,...,-0.009454,0.036102,0.005687,-0.143104,-0.000500,0.223941,-0.227735,0.241329,0.105254,-0.200857
7,-0.087149,0.234833,0.242877,0.362581,0.201592,0.486633,0.611271,1.666151,-0.662167,-0.706300,...,-0.150879,-0.119336,-0.140349,-0.260593,-0.071400,0.103041,-0.113742,0.091814,-0.011082,-0.076437
8,0.058444,-0.195307,-0.197006,-0.369971,-0.222242,-0.636206,-0.738536,-0.662167,1.892764,1.003361,...,0.459314,0.398349,0.472036,0.588270,0.386721,-0.206696,0.320568,-0.200886,0.075405,0.208934
9,0.086614,-0.269668,-0.304970,-0.520129,-0.360206,-0.625956,-0.730121,-0.706300,1.003361,2.667018,...,0.614539,0.573669,0.665738,0.855555,0.515641,-0.145898,0.222861,-0.135538,0.231942,0.100210
10,0.062658,-0.351214,-0.519245,-0.359587,-0.585347,-0.073257,-0.013730,-0.012674,0.101480,0.279970,...,0.010475,0.062599,0.187861,0.574164,0.330095,-0.276405,0.062076,-0.433916,0.179799,0.084228
11,0.128866,-0.440518,-0.631992,-0.538614,-0.750539,-0.226463,-0.171366,-0.195360,0.410909,0.673363,...,0.433127,0.463075,0.596820,0.995906,0.640920,-0.323578,0.160863,-0.480021,0.297604,0.125787
12,-0.222274,0.497277,0.662452,0.425216,0.657447,0.251148,0.234468,0.144320,-0.218496,-0.291187,...,-0.080429,-0.074028,-0.081764,-0.341916,-0.211558,0.437388,-0.245373,0.619664,0.086286,-0.293622
13,-0.254434,0.590269,0.797775,0.673384,0.828451,0.169163,0.174132,0.200256,-0.283322,-0.529187,...,-0.276149,-0.319455,-0.347985,-0.723399,-0.330534,0.215573,0.053266,0.356412,-0.219933,0.012105
14,-0.058751,0.358042,0.468078,0.375009,0.474080,0.414250,0.440781,0.333303,-0.474683,-0.556410,...,0.057587,0.055319,-0.065422,-0.410722,-0.222184,0.381222,-0.255188,0.514108,-0.007124,-0.251548
15,0.391457,-0.170787,-0.223233,-0.299431,-0.404705,-0.097126,-0.009454,-0.150879,0.459314,0.614539,...,2.487317,1.667307,1.458557,1.057097,1.010705,-0.102140,0.375966,-0.086464,0.168204,0.216830
16,0.355623,-0.161831,-0.218929,-0.303104,-0.395581,-0.047771,0.036102,-0.119336,0.398349,0.573669,...,1.667307,2.352644,1.377720,1.033907,0.947901,-0.048266,0.281093,-0.028362,0.216549,0.135800
17,0.169712,-0.017286,-0.050840,-0.193548,-0.264747,-0.090829,0.005687,-0.140349,0.472036,0.665738,...,1.458557,1.377720,2.542385,1.120319,1.006409,-0.053456,0.309004,-0.029882,0.317282,0.127383
18,0.083688,-0.137878,-0.218975,-0.360475,-0.414590,-0.202999,-0.143104,-0.260593,0.588270,0.855555,...,1.057097,1.033907,1.120319,2.463417,0.919139,-0.091942,0.200970,-0.109251,0.427649,0.047211
19,0.024917,0.060547,0.033126,-0.032989,-0.168928,-0.118859,-0.000500,-0.071400,0.386721,0.515641,...,1.010705,0.947901,1.006409,0.919139,2.641045,-0.192108,0.412817,-0.219431,0.225530,0.248261
20,-0.091480,0.177718,0.230073,0.065411,0.236628,0.255907,0.223941,0.103041,-0.206696,-0.145898,...,-0.102140,-0.048266,-0.053456,-0.091942,-0.192108,1.268342,-0.422386,0.531893,0.214617,-0.413602
21,0.006105,0.041735,0.054414,0.136320,-0.013723,-0.293825,-0.227735,-0.113742,0.320568,0.222861,...,0.375966,0.281093,0.309004,0.200970,0.412817,-0.422386,2.408434,-0.500798,-0.206739,0.522498
22,-0.136971,0.272186,0.359312,0.116376,0.362405,0.287787,0.241329,0.091814,-0.200886,-0.135538,...,-0.086464,-0.028362,-0.029882,-0.109251,-0.219431,0.531893,-0.500798,1.455768,0.270012,-0.508426
23,-0.110239,0.097487,0.095171,-0.062361,0.012405,0.092117,0.105254,-0.011082,0.075405,0.231942,...,0.168204,0.216549,0.317282,0.427649,0.225530,0.214617,-0.206739,0.270012,1.419027,-0.260788
24,0.059073,-0.050517,-0.060438,0.077358,-0.085023,-0.250184,-0.200857,-0.076437,0.208934,0.100210,...,0.216830,0.135800,0.127383,0.047211,0.248261,-0.413602,0.522498,-0.508426,-0.260788,1.749830

In [10]:
df(skl.get_precision())

          0         1         2
0  0.005754 -0.000186 -0.003589
1 -0.000186  0.004217 -0.003272
2 -0.003589 -0.003272  0.005995

In [22]:
df(skl.noise_variance_)

           0
0   1.639489
1   0.799600
2   0.804014
3   1.522076
4   0.824195
5   1.005153
6   0.989764
7   1.126949
8   0.964568
9   1.491814
10  1.679087
11  1.180465
12  1.017633
13  1.005486
14  1.067968
15  0.689986
16  0.791636
17  1.208843
18  1.249589
19  1.752446
20  0.855384
21  1.795496
22  0.756270
23  1.070885
24  1.268337

In [3]:
#estadisticos del programa
import statsmodels.formula.api as smf #Libreria que permite calcular los datos
import pandas as pd
#Se lee el archivo y/o dataset en formato csv
dfile = pd.read_csv('./Estadisticas_portal_Anterior.csv')

#Se establece el modelo de regresion lineal a partir del OLS (modelos cuadrados
#por minimos cuadrados)
reg = smf.ols('Numero_de_Visitas ~ Votos_Positivos + Votos_Negativos', data=dfile)
# se ajusta la respuesta
res = reg.fit()
# se muetra la respuesta
print(res.summary())
print(res.rsquared)
# print(res.rsquared)

                            OLS Regression Results
==============================================================================
Dep. Variable:      Numero_de_Visitas   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.786
Method:                 Least Squares   F-statistic:                     4205.
Date:                Fri, 08 Oct 2021   Prob (F-statistic):               0.00
Time:                        02:27:58   Log-Likelihood:                -22707.
No. Observations:                2295   AIC:                         4.542e+04
Df Residuals:                    2292   BIC:                         4.544e+04
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         494.6324    101.414      4.877      0.000     295.759     693.506
Votos_Positivos    10.3501      2.738      3.781      0.000       4.982      15.719
Votos_Negativos    29.9976      0.327     91.623      0.000      29.356      30.640
==============================================================================
Omnibus:                     1510.818   Durbin-Watson:                   1.884
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15446127.070
Skew:                           1.218   Prob(JB):                         0.00
Kurtosis:                     404.898   Cond. No.                         310.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.7858526215011776